services:
  - type: web
    name: vqm-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_USER
        value: admin_vqm
      - key: DATABASE_PASSWORD
        value: BzG45n71A3ZHl06j7vzzs5Ws2odyW3Ad
      - key: DATABASE_HOST
        value: dpg-cvrnntogjchc73be7fd0-a
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        value: vqm_db
      - key: SECRET_KEY
        value: c837a9c0a6767aff0ed01ef3f0cbd60c