"""Actualizar permisos_usuarios

Revision ID: 07eb597ad406
Revises: f58ff0888f5e
Create Date: 2025-04-14 11:55:31.688643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07eb597ad406'
down_revision = 'f58ff0888f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permisos_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departamento', sa.String(), nullable=False))
        batch_op.drop_column('grupo')
        batch_op.drop_column('permiso_edicion')
        batch_op.drop_column('permiso_desbloqueo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permisos_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permiso_desbloqueo', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('permiso_edicion', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('grupo', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('departamento')

    # ### end Alembic commands ###
