"""Corrección id duplicado tabla correos

Revision ID: 1212b54feff7
Revises: b784805d7c08
Create Date: 2025-04-01 12:25:19.351925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1212b54feff7'
down_revision = 'b784805d7c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correos_usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('correos_usuarios_usuario_id_fkey', type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correos_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('correos_usuarios_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
