"""Cambios en fechas de la bbdd

Revision ID: 382501ba8f43
Revises: 928a02f6d377
Create Date: 2025-05-15 09:57:53.747982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382501ba8f43'
down_revision = '928a02f6d377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vqm_temperatura_resumen',
    sa.Column('maquina', sa.String(), nullable=True),
    sa.Column('trimestre_anio', sa.String(), nullable=True),
    sa.Column('estado_actual', sa.String(), nullable=True),
    sa.Column('fecha_ultima_nc', sa.Date(), nullable=True),
    sa.Column('fecha_ultima_validacion', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vqm_temperatura_mi10_resumen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vqm_temperatura_mi10_resumen',
    sa.Column('maquina', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trimestre_anio', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ultima_fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estado_trimestre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('detalle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vqm_temperatura_mi10_resumen_pkey')
    )
    op.drop_table('vqm_temperatura_resumen')
    # ### end Alembic commands ###
