"""Añado tabla nueva para resumen de registros de VQM de temperaturas

Revision ID: 928a02f6d377
Revises: f0e19d4b32f8
Create Date: 2025-05-15 09:47:26.214355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928a02f6d377'
down_revision = 'f0e19d4b32f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vqm_temperatura_mi10_resumen',
    sa.Column('maquina', sa.String(), nullable=False),
    sa.Column('trimestre_anio', sa.String(), nullable=False),
    sa.Column('ultima_fecha', sa.Date(), nullable=True),
    sa.Column('estado_trimestre', sa.String(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vqm_temperatura_mi10_resumen')
    # ### end Alembic commands ###
