"""Ampliar correos_usuarios con email, nombre, departamento

Revision ID: b784805d7c08
Revises: 79fe43275531
Create Date: 2025-04-01 11:56:49.685170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b784805d7c08'
down_revision = '79fe43275531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correos_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('departamento', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correos_usuarios', schema=None) as batch_op:
        batch_op.drop_column('departamento')
        batch_op.drop_column('nombre')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
