"""Cambios en el resumen de registros VQM Temp

Revision ID: c2950ae0ca3a
Revises: 382501ba8f43
Create Date: 2025-05-15 11:52:57.723462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2950ae0ca3a'
down_revision = '382501ba8f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vqm_temperatura_resumen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_fecha', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('origen', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('fecha_evento', sa.Date(), nullable=False))
        batch_op.alter_column('maquina',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('estado_actual')
        batch_op.drop_column('fecha_ultima_nc')
        batch_op.drop_column('trimestre_anio')
        batch_op.drop_column('fecha_ultima_validacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vqm_temperatura_resumen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ultima_validacion', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('trimestre_anio', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_ultima_nc', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estado_actual', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('maquina',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('fecha_evento')
        batch_op.drop_column('origen')
        batch_op.drop_column('estado')
        batch_op.drop_column('grupo_fecha')

    # ### end Alembic commands ###
