"""Cambio de float a string el vqm_temp_mi

Revision ID: dcb5eca95ee9
Revises: c2950ae0ca3a
Create Date: 2025-05-21 11:32:51.254861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb5eca95ee9'
down_revision = 'c2950ae0ca3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vqm_temperatura_mi10', schema=None) as batch_op:
        batch_op.alter_column('num_ml_dia',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('vqm_temperatura_resumen', schema=None) as batch_op:
        batch_op.alter_column('maquina',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('grupo_fecha',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('origen',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('fecha_evento',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vqm_temperatura_resumen', schema=None) as batch_op:
        batch_op.alter_column('fecha_evento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('origen',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('grupo_fecha',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('maquina',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('vqm_temperatura_mi10', schema=None) as batch_op:
        batch_op.alter_column('num_ml_dia',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
