"""Añadir tabla intermedia notificaciones_usuarios y modelo TipoNotificacion

Revision ID: f0e19d4b32f8
Revises: 07eb597ad406
Create Date: 2025-05-08 09:57:28.530325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e19d4b32f8'
down_revision = '07eb597ad406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('notificaciones_usuarios',
    sa.Column('correo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['correo_id'], ['correos_usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_notificacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('correo_id', 'tipo_id')
    )
    with op.batch_alter_table('correos_usuarios', schema=None) as batch_op:
        batch_op.drop_column('tipo_notificacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correos_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_notificacion', sa.VARCHAR(), autoincrement=False, nullable=False))

    op.drop_table('notificaciones_usuarios')
    op.drop_table('tipos_notificacion')
    # ### end Alembic commands ###
