"""Añadir campos a trtamieto_nc_vqm

Revision ID: f58ff0888f5e
Revises: ebd43869e745
Create Date: 2025-04-08 10:19:19.618408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58ff0888f5e'
down_revision = 'ebd43869e745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tratamiento_nc_vqm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('causa_fallo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resuelto_producto', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('acciones_producto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('traza_producto_nombre', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('afecta_producto', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resuelto_proceso', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('acciones_proceso', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('afecta_proceso', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comentarios_validacion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('producto_nc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('acciones_producto_nc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tratamiento_nc_vqm', schema=None) as batch_op:
        batch_op.drop_column('acciones_producto_nc')
        batch_op.drop_column('producto_nc')
        batch_op.drop_column('comentarios_validacion')
        batch_op.drop_column('afecta_proceso')
        batch_op.drop_column('acciones_proceso')
        batch_op.drop_column('resuelto_proceso')
        batch_op.drop_column('afecta_producto')
        batch_op.drop_column('traza_producto_nombre')
        batch_op.drop_column('acciones_producto')
        batch_op.drop_column('resuelto_producto')
        batch_op.drop_column('causa_fallo')

    # ### end Alembic commands ###
